name: crm-system

services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5003:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - crm_system_net

volumes:
  postgres-data:

networks:
  crm_system_net:
