# Generated by Django 5.2.5 on 2025-08-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_cost_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Услуга", "verbose_name_plural": "Услуги"},
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Наименование услуги"
            ),
        ),
    ]
