# Generated by Django 5.2.5 on 2025-08-31 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
        ("customers", "0002_alter_customer_created_at_alter_customer_updated_at"),
        ("products", "0004_alter_product_options_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contract",
                to="customers.customer",
                verbose_name="Клиент",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="product",
            field=models.ManyToManyField(
                related_name="contracts", to="products.product", verbose_name="Услуга"
            ),
        ),
    ]
