# Generated by Django 5.2.5 on 2025-08-31 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contract_customer_contract_product"),
        ("customers", "0002_alter_customer_created_at_alter_customer_updated_at"),
        ("leads", "0005_rename_active_lead_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="lead",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="leads.lead",
                verbose_name="Лид",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="customers.customer",
                verbose_name="Клиент",
            ),
        ),
    ]
