# Generated by Django 5.2.5 on 2025-08-31 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_contract_lead_alter_contract_customer"),
        ("products", "0004_alter_product_options_alter_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="product",
        ),
        migrations.AddField(
            model_name="contract",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="products.product",
                verbose_name="Услуга",
            ),
        ),
    ]
