# Generated by Django 5.2.5 on 2025-08-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_contract_check_date_constraint"),
        ("customers", "0002_alter_customer_created_at_alter_customer_updated_at"),
        ("leads", "0005_rename_active_lead_is_active"),
        ("products", "0004_alter_product_options_alter_product_name"),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="contract",
            name="check_date_constraint",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lt", models.F("end_date"))),
                name="check_date_constraint",
                violation_error_message="Дата начала действия контракта                 должна быть раньше даты его окончания",
            ),
        ),
    ]
