# Generated by Django 5.2.5 on 2025-08-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0006_alter_contract_check_date_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[("NEW", "новый"), ("COMPLETED", "исполнен")],
                default="NEW",
                verbose_name="Статус",
            ),
        ),
    ]
