# Generated by Django 5.2.5 on 2025-08-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0007_contract_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
        ),
    ]
