# Generated by Django 5.2.5 on 2025-09-01 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0008_alter_contract_created_at_alter_contract_updated_at"),
        ("customers", "0002_alter_customer_created_at_alter_customer_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="customers.customer",
                verbose_name="Клиент",
            ),
        ),
    ]
