# Generated by Django 5.2.5 on 2025-09-01 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0009_alter_contract_customer"),
        ("customers", "0002_alter_customer_created_at_alter_customer_updated_at"),
        ("leads", "0006_alter_lead_is_active"),
        ("products", "0004_alter_product_options_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="customers.customer",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="lead",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="leads.lead",
                verbose_name="Лид",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="products.product",
                verbose_name="Услуга",
            ),
        ),
    ]
