# Generated by Django 5.2.5 on 2025-09-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0010_alter_contract_customer_alter_contract_lead_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="lead",
        ),
    ]
