# Generated by Django 5.2.5 on 2025-09-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0011_remove_contract_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
