# Generated by Django 5.2.5 on 2025-09-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0012_contract_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
    ]
