# Generated by Django 5.2.5 on 2025-09-10 15:38

import contracts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0013_alter_contract_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.FileField(
                        upload_to=contracts.models.upload_contract_file,
                        verbose_name="Файл",
                    ),
                ),
                ("alt", models.CharField(default="contract-file", max_length=100)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file",
                        to="contracts.contract",
                        verbose_name="Контракт",
                    ),
                ),
            ],
        ),
    ]
