# Generated by Django 5.2.5 on 2025-09-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0014_contractfile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContractFile",
        ),
    ]
