# Generated by Django 5.2.5 on 2025-09-10 18:28

import contracts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0015_delete_contractfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="file",
            field=models.FileField(
                null=True,
                upload_to=contracts.models.upload_contract_file,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="Файл контракта",
            ),
        ),
    ]
