# Generated by Django 5.2.5 on 2025-09-05 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0004_alter_product_options_alter_product_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Наименование")),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Бюджет кампании"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала действия кампании"),
                ),
                (
                    "end_date",
                    models.DateField(verbose_name="Дата окончания действия кампании"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advertisements",
                        to="products.product",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рекламная кампания",
                "verbose_name_plural": "Рекламные кампании",
            },
        ),
    ]
