# Generated by Django 5.2.5 on 2025-09-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0001_initial"),
        ("products", "0004_alter_product_options_alter_product_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="advertisement",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lt", models.F("end_date"))),
                name="start_date_lt_end_date_constraint",
                violation_error_message="Дата начала должна быть меньше даты окончания",
            ),
        ),
    ]
