# Generated by Django 5.2.5 on 2025-09-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0002_advertisement_start_date_lt_end_date_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="promotion_channel",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Канал продвижения"
            ),
        ),
    ]
