# Generated by Django 5.2.5 on 2025-08-30 20:05

import leads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={"verbose_name": "Лид", "verbose_name_plural": "Лиды"},
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[leads.models.validate_phone],
                verbose_name="Телефон",
            ),
        ),
    ]
