# Generated by Django 5.2.5 on 2025-08-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_alter_lead_options_alter_lead_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(blank=True, max_length=120, verbose_name="Email"),
        ),
    ]
