# Generated by Django 5.2.5 on 2025-08-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_alter_lead_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
