# Generated by Django 5.2.5 on 2025-08-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_lead_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="active",
            new_name="is_active",
        ),
    ]
