# Generated by Django 5.2.5 on 2025-08-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0005_rename_active_lead_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
    ]
