# Generated by Django 5.2.5 on 2025-09-06 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0002_advertisement_start_date_lt_end_date_constraint"),
        ("leads", "0006_alter_lead_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="ad",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="leads",
                to="advertisements.advertisement",
                verbose_name="Рекламная кампания",
            ),
        ),
    ]
