# Generated by Django 5.2.5 on 2025-08-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
